flyway.url=jdbc:postgresql://localhost:5433/odiseo
flyway.user=postgres
flyway.password=123456
flyway.schemas=odiseo,extensions,anon,public,audit
flyway.locations=filesystem:./migrations
flyway.baselineOnMigrate=true