-- ==========================================
-- ROLES AND PERMISSIONS (Clean DB Architecture)
-- ==========================================

CREATE ROLE andrea;
ALTER ROLE andrea WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE frank;
ALTER ROLE frank WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE jhon;
ALTER ROLE jhon WITH SUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:aEAZqmracvONWtoLdILOkg==$FrrkEmmZzsV6l1HGYbs9gf5G7wLA0lyHTpyeeLnQgyM=:UU1XISvYjhSGyndWIj1m1bcm9BLEjBrLeD7oCTUzh0s=';
CREATE ROLE usuario_lectura;
ALTER ROLE usuario_lectura WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS;
